### ISSUE TITLE
Update to Country for US Infection Level

### ISSUE THREAD

**Issue by krishnac7** [Call-for-Code/Solution-Starter-Kit-Communication-2020#24]
The covid19 API has the US listed as "united states of America" so the country code has to be updated before calling functions to get proper response
<img width="700" alt="Screenshot 2020-04-06 at 1 46 31 PM" src="https://user-images.githubusercontent.com/7543641/78537561-4d006180-780d-11ea-80f6-4030e548a3b7.png">

**Comment by johnwalicki** [comment]
Thanks for the report - Fixed in recent commits.
