### ISSUE TITLE
Using COVID-19 API to get results for other countries

### ISSUE THREAD

**Issue by krishnac7** [Call-for-Code/Solution-Starter-Kit-Communication-2020#25]
We can update the country parameter to '@sys-location' to make the pattern more functional to fetch other country results as well
<img width="621" alt="Screenshot 2020-04-06 at 1 59 30 PM" src="https://user-images.githubusercontent.com/7543641/78538662-f5fb8c00-780e-11ea-969f-24ebcbcbd874.png">

The response text can also be updated with the same system entity to have proper responses
<img width="511" alt="Screenshot 2020-04-06 at 2 01 10 PM" src="https://user-images.githubusercontent.com/7543641/78538734-17f50e80-780f-11ea-8a5f-4cdb0a5c821b.png">
<img width="413" alt="Screenshot 2020-04-06 at 2 01 55 PM" src="https://user-images.githubusercontent.com/7543641/78538804-31965600-780f-11ea-9df7-62c0f6d5c74b.png">

It might also make sense to rename the Intent and dialog as well :P thanks

**Comment by johnwalicki** [comment]
@moficodes - Can you look at this suggestion?

**Comment by Hero-Repo** [comment]
Great work guys, love to connect and network.

**Comment by transdigiware** [comment]
saya ingin untuk negara saya Indonesia

**Comment by johnwalicki** [comment]
Hi @krishnac7 
"I want for my country Indonesia" - Great suggestion.  We don't currently provide translations for the COVID chat bot Q&A. Watson Assistant does support a variety of languages. Maybe you can translate and provide it locally in one of these languages ?

https://cloud.ibm.com/docs/assistant?topic=assistant-language-support

**Comment by krishnac7** [comment]
@johnwalicki will work on it

**Comment by moficodes** [comment]
I think this make sense. @krishnac7 thank you for the suggestion and the investigation.

Another way to improve this would probably be to delete this intent + dialog entirely since 
We have a `how_many_cases` intent. That as a reply asks for a specific country. 

Open to discussion.

**Comment by jiportilla** [comment]
Another issue I found was regarding metrics from Taiwan, in the original source - https://api.covid19api.com/summary is listed as `"Country": "Taiwan, Republic of China",
"CountryCode": "TW",`, however when  the Function makes the call, it shows ```response": {
"result": {
"error": "did not find country"```  FYI - https://en.wikipedia.org/wiki/Political_status_of_Taiwan

**Comment by thomassuedbroecker** [comment]
@jiportilla That's related to bug, I would say: https://github.com/Call-for-Code/Solution-Starter-Kit-Communication-2020/pull/34

**Comment by johnwalicki** [comment]
We're pivoting the Chatbot data webhook away from covid19api to use the TWC Disease Tracker API instead.
Closing this issue.
