### ISSUE TITLE
webhook error

### ISSUE THREAD

**Issue by Nickblaq** [Call-for-Code/Solution-Starter-Kit-Communication-2020#31]
Results:
{
  "error": {
    "message": "Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password and iam_access_token.",
    "name": "Error",
    "stack": "Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password and iam_access_token.\n    at DiscoveryV1.BaseService.initCredentials (/node_modules/watson-developer-cloud/lib/base_service.js:249:23)\n

**Comment by zacaintmyname** [comment]
Getting the same error! Bump up!

**Comment by johnwalicki** [comment]
@Nickblaq @zacaintmyname - It looks like you didn't provide the api_key of your Watson Discovery service instance.  See the screenshot in the tutorial.

If you want to make a call to the Discovery service, you need to set some parameters that lets you call the IAM-enabled service. On the left, click on the Parameters tab. Add the following parameters: api_key, url, collection_id, and env_id. The collection_id and env_id are the values you noted from the Watson Discovery service in the previous steps.

**Comment by Nickblaq** [comment]
Thanks it worked! but i still can't return data from the covid-19 summary endpoint, i keep getting empty array instead. Any solution?

**Comment by zacaintmyname** [comment]
when you copy the code into your IBM Cloud Functions service, make sure you paste this code from:[https://github.com/Call-for-Code/Solution-Starter-Kit-Communication-2020/blob/master/starter-kit/webhook/action/covid-webhook.js](url)

I suggest if you go to Github `RAW`, and copy paste that would reduce indentation errors. 

You should already included your parameters as shared in the tutorial. 

Then go to code >> invoke with parameters >> invoke:
`{
"":"api",
"country":"thailand"
}`

You should be able to see the results now. 
I got mine working!

**Comment by Emirkaz** [comment]
> @Nickblaq @zacaintmyname - It looks like you didn't provide the api_key of your Watson Discovery service instance. See the screenshot in the tutorial.
> 
> If you want to make a call to the Discovery service, you need to set some parameters that lets you call the IAM-enabled service. On the left, click on the Parameters tab. Add the following parameters: api_key, url, collection_id, and env_id. The collection_id and env_id are the values you noted from the Watson Discovery service in the previous steps.

I'm

**Comment by Emirkaz** [comment]
Its no working for me....I'm getting the same error
i have tried inputing the parameters but still not working


{
  "error": {
    "message": "Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password and iam_access_token.",
    "name": "Error",
    "stack": "Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password and iam_access_token.\n    at DiscoveryV1.BaseService.initCredentials (/node_modules/watson-developer-cloud/lib/base_service.js:249:23)\n    at DiscoveryV1.BaseService (/node_modules/watson-developer-cloud/lib/base_service.js:95:29)\n    at DiscoveryV1 [as constructor] (/node_modules/watson-developer-cloud/discovery/v1-generated.js:58:28)\n    at new DiscoveryV1 (/node_modules/watson-developer-cloud/discovery/v1.js:19:23)\n    at NodeActionRunner.main [as userScriptMain] (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:55:23)\n    at Promise (/nodejsAction/runner.js:73:35)\n    at new Promise (<anonymous>)\n    at NodeActionRunner.run (/nodejsAction/runner.js:71:16)\n    at doRun (/nodejsAction/src/service.js:196:14)\n    at runCode (/nodejsAction/src/service.js:141:20)\n    at /nodejsAction/platform/platform.js:125:17\n    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)\n    at next (/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)\n    at /node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)\n    at next (/node_modules/express/lib/router/index.js:275:10)\n    at /node_modules/body-parser/lib/read.js:130:5\n    at invokeCallback (/node_modules/raw-body/index.js:224:16)\n    at done (/node_modules/raw-body/index.js:213:7)\n    at IncomingMessage.onEnd (/node_modules/raw-body/index.js:273:7)"
  }
}
Logs:
[]

**Comment by zacaintmyname** [comment]
Hey Emirkaz, check this out: https://developer.ibm.com/conferences/c4cdc-take-on-covid19/crisis-communication-starter-kit-extend-your-covid-19-chatbot/ 

Should be able to troubleshoot your mistake here.

**Comment by InnoOkeke** [comment]
When I set parameters(type:API, country:Nigeria) I get total results? Why? What am I not getting right?

Thanks

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by zacaintmyname** [comment]
the parameters in the Cloud Functions tool is reserved for the API Key, URL, Env and collection ID. 

If you key in the right credentials, then this below will work

> Then go to code >> invoke with parameters >> invoke:
> { "type":"api", "country":"(of your choice)" }

**Comment by InnoOkeke** [comment]
All right thanks. It later worked.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by zacaintmyname** [comment]
Admins i think we can close this issue.

**Comment by Emirkaz** [comment]
> Hey Emirkaz, check this out: https://developer.ibm.com/conferences/c4cdc-take-on-covid19/crisis-communication-starter-kit-extend-your-covid-19-chatbot/
> 
> Should be able to troubleshoot your mistake here.

Thanks Sir
its really helpful

**Comment by moficodes** [comment]
@johnwalicki i think we are good to close.
