### ISSUE TITLE
Recommended approach for styling?

### ISSUE THREAD

**Issue by easherma** [Call-for-Code/Solution-Starter-Kit-Communication-2020#32]
Hi there, 

Is there an expected way to customize styling for the app after including it on a page? I could see some value in being able to call the script with some custom theme parameters like typeface, background color, and logo.

**Comment by InnoOkeke** [comment]
I couldn't get to style the bot. But I added it to my wordpress based website with a plugin and was able to style the interface with the plugin.
________________________________

**Comment by Hero-Repo** [comment]
Please am new to this but can anyone help me out on how to proceed. I am beginner with 💉 experience 🙂

**Comment by InnoOkeke** [comment]
Just follow the instructions carefully. Whenever you come across a problem, drop a question and we'll help solve it.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Hero-Repo** [comment]
Great I will thanks and appreciated

**Comment by InnoOkeke** [comment]
You're welcome

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by lidderupk** [comment]
> Hi there,
> 
> Is there an expected way to customize styling for the app after including it on a page? I could see some value in being able to call the script with some custom theme parameters like typeface, background color, and logo.

@easherma, which application are you trying to stylize? The Node.js application is just an example of how to developer something like this from scratch. You can style it however you like. Another option is to create the Assistant and then add a `Web Chat Integration`. That let's you style the little chat bubble and the messaging experience a little more. However, that is only available in the Plus Plan, which you can try for free fo a limited time.

<img width="933" alt="image" src="https://user-images.githubusercontent.com/3187457/79501509-01a33b80-7fe3-11ea-95cc-c1b556804a8a.png">

**Comment by lidderupk** [comment]
> Please am new to this but can anyone help me out on how to proceed. I am beginner with 💉 experience 🙂

@Hero-Repo, did you have specific questions we can help with?

**Comment by johnwalicki** [comment]
There are several ways to create custom Node-RED-Dashboard styles / themes
See the theme section at
https://flows.nodered.org/node/node-red-dashboard

Closing ticket.
