### ISSUE TITLE
microphone node does not display on dashboard

### ISSUE THREAD

**Issue by moturivn** [Call-for-Code/Solution-Starter-Kit-Communication-2020#36]
Hi,

I have copied the node red flow and accessed my dashboard. I saw that there was no microphone button for me to ask a question. I have seen that the node displays on your dashboard so I can't really say its a problem with the node. Could you please help me out with this?

![image](https://user-images.githubusercontent.com/40521993/80908220-2ccca100-8cec-11ea-827e-1adcdc28d8e7.png)

Thanks

**Comment by johnwalicki** [comment]
Hi - Thanks for the report - we've been chasing this bug for a few days.  Good news is that there is a new version of node-red-node-ui-microphone v0.1.4 that fixes this problem.  If you restage your IBM Cloud CF application to pick up the new version, the microphone will appear.
