### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by ragdeshp** [Call-for-Code/Solution-Starter-Kit-Communication-2020#37]
We are referring to https://developer.ibm.com/tutorials/crisis-communication-chatbot-watson-assistant-webhook-integration-discovery-covid-data/ starter kit and we could find that the documentation has a typo.

We see twcApiKey and url parameters have the same description. The url here should have been the discovery service url.

**Comment by johnwalicki** [comment]
@emilyannmitchell I opened a PR against the IBM Developer documentation. Please review / merge when you get a chance.

**Comment by emilyannmitchell** [comment]
@johnwalicki Merged

**Comment by johnwalicki** [comment]
Super - Closing ticket
