### ISSUE TITLE
PROBLEM SETTING PARAMETERS IN WEBHOOK

### ISSUE THREAD

**Issue by cartloslopezjuan** [Call-for-Code/Solution-Starter-Kit-Communication-2020#40]
Hello,

I find an error when adding apikeys and urls as parameeters for the webhook (IBM action function).

See attached image:

[https://i.stack.imgur.com/0tdJL.png](url)

![image](https://user-images.githubusercontent.com/66802399/84444273-b5baee80-ac41-11ea-9b45-9f30534e6dd9.png)

The keys or urls appear in red and cant SAVE.

**Comment by jeremybdev** [comment]
Hi,

Try enclosing the API key in double quotes like the other parameters.

**Comment by cartloslopezjuan** [comment]
> Hi,
> 
> Try enclosing the API key in double quotes like the other parameters.

Thank you very much!!

**Comment by johnwalicki** [comment]
Correct - enclose the API key in double quotes but it points out a subtle problem in the documentation.
We can either redo the screenshot (which blurs the API key) so that the blur does not include the 
" ▓▓▓ "
Or we could mention it in the text description.

**Comment by jeremybdev** [comment]
Mentioning it in the text description will be very helpful.

**Comment by cartloslopezjuan** [comment]
I found out that the system-variables for location are not working, so the bot cant really get the information properly from the API or "The Weather Company".
 
 @sys-location has been deprecated.

Please let me know how to solve this problem if possible.

**Comment by johnwalicki** [comment]
I updated the README to specify double quotes.
https://github.com/Call-for-Code/Solution-Starter-Kit-Communication-2020/commit/b9432227c0bdfdc88d49422e4fa5eb12b5bbf1bb
