### ISSUE TITLE
Problem Pushing APP from CLI**I dont know how to create a Space from CLI**

### ISSUE THREAD

**Issue by cartloslopezjuan** [Call-for-Code/Solution-Starter-Kit-Communication-2020#41]
I am stuck in this part of the tutorial:

![image](https://user-images.githubusercontent.com/66802399/84582258-1be27580-adea-11ea-8502-0346eceb9c6a.png)

I dont understand why when I introduce the last terminal command to finish the whole thing, I get this message:

ERROR
_No se ha establecido ninguna organización ni espacio como destino. Utilice 'ibmcloud target -o ORG -s SPACE' para establecer una organización y espacio como destino.

It says ORG and SPACE have not been defined.

The problem is: **I dont know how to create a Space from CLI**, as the documentation I have seen online dont help.

Any recommendation would be of great help, thank you.

Carlos

**Comment by cartloslopezjuan** [comment]
hello?

**Comment by InnoOkeke** [comment]
You'll have to create org and space in your IBM cloud console first. Or follow the process of creating via IBM CLI.
________________________________

**Comment by cartloslopezjuan** [comment]
Thank you. I am using IBM Cli actually as the tutorial states.

The problem is that I creted the organization through console (OK) but cant create the SPACE. Have you got any instructions or guide on it? 

I just found this in internet:
http://cli.cloudfoundry.org/en-US/cf/create-space.html

But these commands do not work, or I dont know how to use

![image](https://user-images.githubusercontent.com/66802399/85560499-feec4480-b62a-11ea-83b7-8b5b5772494b.png)

**Comment by InnoOkeke** [comment]
If you've created the org and space. You need to target the org from the CLI
________________________________

**Comment by cartloslopezjuan** [comment]
No **I could not create the SPACE.**

I need to know the exact commands to do this please.

**Comment by InnoOkeke** [comment]
https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-create_orgs

Check this link.
________________________________

**Comment by cartloslopezjuan** [comment]
Great, now I completed the push.

Now both services (Cloud Foundry App and Watson Assistant are running in IBM CLoud). 

**BUT I FOUND A NEW PROBLEM:**

![image](https://user-images.githubusercontent.com/66802399/85715783-17706380-b6ec-11ea-927d-301e532c078a.png)


How can I solve it? Is it a problem of conextion between Cloud Foundry app and Watson Assistant?

**Comment by InnoOkeke** [comment]
No. Refresh the page. It should work properly.
________________________________
